name: app_perufest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  intl: ^0.18.0
  provider: ^6.0.0
  crypto: ^3.0.3
  bcrypt: ^1.1.3
  http: ^1.1.0
  image_picker: ^1.0.4
  supabase_flutter: ^2.0.0
  timezone: ^0.9.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  url_launcher: ^6.2.2
  flutter_local_notifications: ^17.2.2
  path_provider: ^2.1.1
  open_file: ^3.3.2
  file_picker: ^10.3.3
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FF6B35"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/